"""Contract tests: the REAL app, generated requests, replayed network.

Why this tree lives apart from ``src/tests/backend``
----------------------------------------------------
25 of the 33 files under ``src/tests/backend`` replace ``sys.modules["azure"]``,
``sys.modules["agent_framework"]`` and friends with ``Mock()`` at import time.
Those stubs are process-global and survive into every module imported after
them, so a test that wants the real code cannot share a pytest session with
them — ``src/tests/backend/conftest.py`` documents the same hazard for the
middleware chain.

The cut here is at the socket, not at the import:

* the FastAPI app is the real one (``app.py`` → ``include_router(app_v4)``);
* the requests are generated by schemathesis from the app's own OpenAPI
  schema — no request is written by hand;
* only outbound HTTP (Foundry / AOAI / Cosmos / AAD) is served from VCR
  cassettes recorded once against real Azure.

Running
-------
Not in ``testpaths``: this is a separate pytest session on purpose.

    # replay (offline, the normal mode — fails if a call has no cassette)
    uv run --project src/backend pytest src/tests/contract -q

    # record (needs the real src/backend/.env + az login). Delete the cassette
    # first, then use new_episodes — NEVER once: with the SHARED cassette the
    # first test creates the file and `once` write-protects it for every test
    # after, so the rest of the "recording" silently runs as replay and their
    # outbound calls never get taped (231 CannotOverwrite inits in one run).
    # new_episodes serves what is already taped and appends what is missing.
    rm src/tests/contract/cassettes/*/chat_flow.yaml
    uv run --project src/backend pytest src/tests/contract -q \
        --record-mode=new_episodes --contract-live
    uv run --project src/backend python src/tests/contract/lint_cassette.py
"""

import os
import re
import sys
from pathlib import Path

import pytest
import schemathesis
from schemathesis import GenerationMode

_REPO_ROOT = Path(__file__).resolve().parents[3]
_BACKEND = _REPO_ROOT / "src" / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))


def pytest_addoption(parser):
    parser.addoption(
        "--contract-live",
        action="store_true",
        default=False,
        help="Load src/backend/.env so recording talks to real Azure. "
        "Without it the app boots on inert placeholder config.",
    )


def pytest_configure(config):
    """Configure the app's environment BEFORE anything imports app.py.

    In replay mode the values are inert placeholders: every outbound call is
    served by a cassette, so no real endpoint is ever resolved. In live mode
    the real .env wins, because recording must hit the real services.
    """
    if config.getoption("--contract-live"):
        env_file = _BACKEND / ".env"
        if not env_file.exists():
            raise pytest.UsageError(f"--contract-live needs {env_file}")
        from dotenv import load_dotenv

        load_dotenv(env_file, override=True)

        return

    # Replay mode. These are OVERRIDES, not defaults: `app_config` calls
    # `load_dotenv()` at import and the devcontainer exports some of these
    # too, so a `setdefault` would leave the real subscription's endpoints in
    # place and the suite would try to reach them. Set here (before app.py is
    # imported) they also win over load_dotenv, which never overrides.
    for key, value in {
        "APP_ENV": "dev",
        "AZURE_OPENAI_ENDPOINT": "https://contract.openai.azure.com/",
        "AZURE_AI_AGENT_ENDPOINT": "https://contract.services.ai.azure.com/api/projects/contract",
        "AZURE_AI_PROJECT_ENDPOINT": "https://contract.services.ai.azure.com/api/projects/contract",
        "AZURE_AI_PROJECT_NAME": "contract-project",
        "AZURE_AI_RESOURCE_GROUP": "contract-rg",
        "AZURE_AI_SUBSCRIPTION_ID": "00000000-0000-0000-0000-000000000000",
        "AZURE_STORAGE_BLOB_URL": "https://contract.blob.core.windows.net",
        "COSMOSDB_ENDPOINT": "https://contract.documents.azure.com:443/",
        "COSMOSDB_DATABASE": "contract-db",
        "COSMOSDB_CONTAINER": "contract-container",
        "MCP_SERVER_ENDPOINT": "http://localhost:9000/mcp",
        "CHAT_ORCHESTRATOR_AGENT_NAME": "contract-orchestrator",
        # Placeholder, NOT empty: use_rag agents require a search endpoint at
        # CONSTRUCTION time — with "" the factory failed every RAG agent,
        # init_team 400'd "participants cannot be empty", and replay diverged
        # from the recorded flow (which built them fine under the real .env).
        # Actual search/embedding HTTP is served from the cassette like every
        # other dependency; the azure_host matcher classes *.search.windows.net.
        "AZURE_AI_SEARCH_ENDPOINT": "https://contract.search.windows.net",
        # Telemetry off: the exporter and QuickPulse ping Azure from
        # background threads, which has nothing to do with the contract and
        # drowns the report in cassette misses.
        "APPLICATIONINSIGHTS_CONNECTION_STRING": "",
        "OTEL_SDK_DISABLED": "true",
    }.items():
        os.environ[key] = value


@pytest.fixture(scope="session")
def app():
    """The real FastAPI application — same object uvicorn serves."""
    from app import app as fastapi_app

    return fastapi_app


# ── Close starlette_testclient's leaked lifespan streams ───────────────────
#
# schemathesis drives ASGI apps through starlette_testclient.TestClient,
# whose __enter__ creates two in-memory stream pairs for the lifespan
# channel and whose __exit__ closes the portal but NEVER the streams —
# every example leaked a pair into the ResourceWarning gate (probe:
# 26/26 creation stacks at _testclient.py __enter__; zero from the app).
# Closing them after the original __exit__ is closing the leak at its
# owner layer, not silencing the gate. MemoryObject*Stream.close() is
# synchronous and idempotent, so it is safe after the portal is gone.
def _patch_testclient_stream_leak():
    import starlette_testclient

    _orig_exit = starlette_testclient.TestClient.__exit__

    def _exit(self, *args):
        try:
            return _orig_exit(self, *args)
        finally:
            for stapled in (
                getattr(self, "stream_send", None),
                getattr(self, "stream_receive", None),
            ):
                for half in (
                    getattr(stapled, "send_stream", None),
                    getattr(stapled, "receive_stream", None),
                ):
                    if half is not None:
                        half.close()

    starlette_testclient.TestClient.__exit__ = _exit


_patch_testclient_stream_leak()


# ── VCR: the only boundary that is faked ───────────────────────────────────

_SECRET_HEADERS = [
    "authorization",
    "api-key",
    "cookie",
    "set-cookie",
    "x-ms-client-principal",
    "x-ms-client-principal-id",
    "x-ms-client-principal-name",
    "ocp-apim-subscription-key",
]

_SECRET_JSON_KEYS = (
    "access_token",
    "refresh_token",
    "id_token",
    "client_secret",
    "assertion",
    "primaryMasterKey",
    "secondaryMasterKey",
    # Identity GUIDs in Foundry agent-definition bodies. Copilot code
    # scanning flagged them in a recorded cassette (e9ef476d edited the tape
    # by hand); scrubbing here makes every future recording come out clean.
    "principal_id",
    "client_id",
)


_TELEMETRY_HOST_MARKERS = (
    "applicationinsights.azure.com",
    "livediagnostics.monitor.azure.com",
    "monitor.azure.com",
    "dc.services.visualstudio.com",
)


# Real Azure resource hosts → the contract placeholders replay boots on, so
# future recordings carry no subscription resource names. (The Copilot-autofix
# version of this normalization never ran: `\\.` inside a raw string matches a
# literal backslash — the patterns could not match a URL — and
# `request._replace` does not exist on vcr's Request, which mutates via
# attribute assignment like vcr's own filters do.)
_HOST_PLACEHOLDERS = (
    (
        re.compile(r"https://[^/]+\.blob\.core\.windows\.net"),
        "https://contract.blob.core.windows.net",
    ),
    (
        re.compile(r"https://[^/]+\.documents\.azure\.com(?::443)?"),
        "https://contract.documents.azure.com:443",
    ),
    (
        re.compile(r"https://[^/]+\.services\.ai\.azure\.com"),
        "https://contract.services.ai.azure.com",
    ),
    (
        re.compile(r"https://[^/]+\.openai\.azure\.com"),
        "https://contract.openai.azure.com",
    ),
)


def _drop_telemetry(request):
    """Drop telemetry traffic and scrub requests so cassettes are safe + replayable."""
    host = (request.host or "").lower()
    if any(marker in host for marker in _TELEMETRY_HOST_MARKERS):
        return None

    import json

    for pattern, placeholder in _HOST_PLACEHOLDERS:
        request.uri = pattern.sub(placeholder, request.uri)

    # Redact large/sensitive JSON payload fields (matching does not include body).
    body = request.body
    if body:
        try:
            text = (
                body.decode("utf-8", "replace")
                if isinstance(body, (bytes, bytearray))
                else str(body)
            )
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                for k in ("messages", "tools", "history"):
                    if k in parsed:
                        parsed[k] = "[REDACTED]"
                request.body = json.dumps(parsed).encode()
        except (ValueError, TypeError, UnicodeDecodeError):
            # Best-effort scrubbing: if payload is not parseable JSON, keep body unchanged.
            pass

    return request


# ── Matching: recorded-vs-replay endpoints differ by design ────────────────
#
# Cassettes are recorded against the REAL subscription (cosmos-<acct>,
# /dbs/macae/colls/chat_sessions); replay boots the app on inert placeholders
# (contract.documents.azure.com, /dbs/contract-db/colls/contract-container).
# Literal host/path matching therefore misses every recorded call. The match
# is on the SERVICE CLASS and the normalized path shape instead — which is
# also what makes the suite runnable in CI, where no real endpoint exists.

_AZURE_HOST_CLASSES = (
    (".documents.azure.com", "cosmos"),
    (".openai.azure.com", "aoai"),
    (".services.ai.azure.com", "foundry"),
    (".blob.core.windows.net", "blob"),
    (".search.windows.net", "search"),
    (".vault.azure.net", "keyvault"),
)


def _host_class(host):
    h = (host or "").lower()
    for suffix, cls in _AZURE_HOST_CLASSES:
        if h.endswith(suffix):
            return cls
    # login.microsoftonline.com etc. — literal match
    return h


def _normalize_path(path):
    # Account, container and Foundry-project names are deployment config,
    # not contract shape.
    path = re.sub(r"/dbs/[^/]+/colls/[^/]+", "/dbs/_/colls/_", path or "")
    return re.sub(r"/api/projects/[^/]+", "/api/projects/_", path)


def _azure_host_matcher(r1, r2):
    assert _host_class(r1.host) == _host_class(r2.host), (
        f"{_host_class(r1.host)} != {_host_class(r2.host)}"
    )


def _azure_path_matcher(r1, r2):
    assert _normalize_path(r1.path) == _normalize_path(r2.path), (
        f"{_normalize_path(r1.path)} != {_normalize_path(r2.path)}"
    )


def pytest_recording_configure(config, vcr):
    vcr.register_matcher("azure_host", _azure_host_matcher)
    vcr.register_matcher("azure_path", _azure_path_matcher)


def _scrub_response(response):
    """Redact credentials from recorded bodies before they hit disk."""
    body = response.get("body", {}).get("string")
    if not body:
        return response
    text = body.decode("utf-8", "replace") if isinstance(body, bytes) else str(body)
    if not any(key in text for key in _SECRET_JSON_KEYS):
        return response
    import json
    import re

    try:
        parsed = json.loads(text)
    except (ValueError, TypeError):
        for key in _SECRET_JSON_KEYS:
            text = re.sub(rf'("{key}"\s*:\s*)"[^"]*"', r'\1"[REDACTED]"', text)
        response["body"]["string"] = text.encode()
        return response

    def _walk(node):
        if isinstance(node, dict):
            return {
                k: ("[REDACTED]" if k in _SECRET_JSON_KEYS else _walk(v))
                for k, v in node.items()
            }
        if isinstance(node, list):
            return [_walk(v) for v in node]
        return node

    response["body"]["string"] = json.dumps(_walk(parsed)).encode()
    return response


@pytest.fixture(scope="session")
def vcr_config():
    return {
        # `record_mode` is deliberately NOT set here. pytest_recording._vcr
        # does `if "record_mode" in merged_config: record_mode = ...`, so a
        # value in this dict overrides --record-mode from the CLI outright and
        # a recording run silently stays in replay. The plugin already
        # defaults to "none", which is the guarantee we want: an outbound call
        # with no cassette raises instead of reaching the network.
        "filter_headers": [(h, "[REDACTED]") for h in _SECRET_HEADERS],
        "filter_post_data_parameters": [
            ("client_secret", "[REDACTED]"),
            ("assertion", "[REDACTED]"),
            ("refresh_token", "[REDACTED]"),
            ("code", "[REDACTED]"),
        ],
        "before_record_response": _scrub_response,
        # Generated requests vary by design, so the recorded upstream call
        # must match on the endpoint, not on the exact payload. Without this
        # every fuzzed variant would miss its cassette. azure_host/azure_path
        # (registered in pytest_recording_configure) compare service class and
        # normalized path shape, so replay works on placeholder config.
        # "query" is REQUIRED: Foundry lists agents with cursor pagination
        # (?after=...) — without query matching, every page request got served
        # the same first page and the SDK cursor-looped forever (init_team
        # hung 14+ min deserializing the same 69KB page). Cursors are stable
        # because record and replay read the same tape.
        "match_on": ["method", "scheme", "azure_host", "port", "azure_path", "query"],
        "allow_playback_repeats": True,
        # localhost is NOT ignored: the app's outbound localhost calls (MCP
        # server :9000, Inspector proxy :16277) must be recorded and replayed
        # like any other dependency — ignoring them let replay talk to
        # whatever happened to be running locally, so the suite's result
        # depended on live services (15 passed recording vs 4 on "replay").
        # The schemathesis→app calls themselves are in-process ASGI and never
        # reach vcr's transport patches; "testserver" is listed defensively.
        "ignore_hosts": [
            "testserver",
        ],
        # Telemetry is not part of any contract — never record it, never
        # count its misses as findings.
        "before_record_request": _drop_telemetry,
        "decode_compressed_response": True,
    }


@pytest.fixture(scope="module")
def vcr_cassette_dir(request):
    return str(Path(__file__).parent / "cassettes" / request.module.__name__)


@schemathesis.hook("map_case")
def force_stable_session_id(_, case):
    if case.meta and case.meta.generation.mode is GenerationMode.NEGATIVE:
        return case

    if case.path in {
        "/api/v4/chat/message",
        "/api/v4/chat/message/stream",
    }:
        if isinstance(case.body, dict):
            case.body["session_id"] = "00000000-0000-0000-0000-000000000123"

    if isinstance(case.path_parameters, dict):
        for k in ("file_id", "session_id"):
            if k in case.path_parameters:
                case.path_parameters[k] = "contract-fixed-id"

    return case
