"""Contract tests: the REAL app, generated requests, replayed network.

Why this tree lives apart from ``src/tests/backend``
----------------------------------------------------
25 of the 33 files under ``src/tests/backend`` replace ``sys.modules["azure"]``,
``sys.modules["agent_framework"]`` and friends with ``Mock()`` at import time.
Those stubs are process-global and survive into every module imported after
them, so a test that wants the real code cannot share a pytest session with
them — ``src/tests/backend/conftest.py`` documents the same hazard for the
middleware chain.

The cut here is at the socket, not at the import:

* the FastAPI app is the real one (``app.py`` → ``include_router(app_v4)``);
* the requests are generated by schemathesis from the app's own OpenAPI
  schema — no request is written by hand;
* only outbound HTTP (Foundry / AOAI / Cosmos / AAD) is served from VCR
  cassettes recorded once against real Azure.

Running
-------
Not in ``testpaths``: this is a separate pytest session on purpose.

    # replay (offline, the normal mode — fails if a call has no cassette)
    uv run --project src/backend pytest src/tests/contract -q

    # record (needs the real src/backend/.env + az login)
    uv run --project src/backend pytest src/tests/contract -q \
        --record-mode=once --contract-live
"""

import os
import sys
from pathlib import Path
import schemathesis
from schemathesis import GenerationMode
import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]
_BACKEND = _REPO_ROOT / "src" / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))


def pytest_addoption(parser):
    parser.addoption(
        "--contract-live",
        action="store_true",
        default=False,
        help="Load src/backend/.env so recording talks to real Azure. "
        "Without it the app boots on inert placeholder config.",
    )


def pytest_configure(config):
    """Configure the app's environment BEFORE anything imports app.py.

    In replay mode the values are inert placeholders: every outbound call is
    served by a cassette, so no real endpoint is ever resolved. In live mode
    the real .env wins, because recording must hit the real services.
    """
    if config.getoption("--contract-live"):
        env_file = _BACKEND / ".env"
        if not env_file.exists():
            raise pytest.UsageError(f"--contract-live needs {env_file}")
        from dotenv import load_dotenv

        load_dotenv(env_file, override=True)

        return

    # Replay mode. These are OVERRIDES, not defaults: `app_config` calls
    # `load_dotenv()` at import and the devcontainer exports some of these
    # too, so a `setdefault` would leave the real subscription's endpoints in
    # place and the suite would try to reach them. Set here (before app.py is
    # imported) they also win over load_dotenv, which never overrides.
    for key, value in {
        "APP_ENV": "dev",
        "AZURE_OPENAI_ENDPOINT": "https://contract.openai.azure.com/",
        "AZURE_AI_AGENT_ENDPOINT": "https://contract.services.ai.azure.com/api/projects/contract",
        "AZURE_AI_PROJECT_ENDPOINT": "https://contract.services.ai.azure.com/api/projects/contract",
        "AZURE_AI_PROJECT_NAME": "contract-project",
        "AZURE_AI_RESOURCE_GROUP": "contract-rg",
        "AZURE_AI_SUBSCRIPTION_ID": "00000000-0000-0000-0000-000000000000",
        "AZURE_STORAGE_BLOB_URL": "https://contract.blob.core.windows.net",
        "COSMOSDB_ENDPOINT": "https://contract.documents.azure.com:443/",
        "COSMOSDB_DATABASE": "contract-db",
        "COSMOSDB_CONTAINER": "contract-container",
        "MCP_SERVER_ENDPOINT": "http://localhost:9000/mcp",
        "CHAT_ORCHESTRATOR_AGENT_NAME": "contract-orchestrator",
        # Telemetry off: the exporter and QuickPulse ping Azure from
        # background threads, which has nothing to do with the contract and
        # drowns the report in cassette misses.
        "APPLICATIONINSIGHTS_CONNECTION_STRING": "",
        "OTEL_SDK_DISABLED": "true",
    }.items():
        os.environ[key] = value


@pytest.fixture(scope="session")
def app():
    """The real FastAPI application — same object uvicorn serves."""
    from app import app as fastapi_app

    return fastapi_app


# ── VCR: the only boundary that is faked ───────────────────────────────────

_SECRET_HEADERS = [
    "authorization",
    "api-key",
    "cookie",
    "set-cookie",
    "x-ms-client-principal",
    "x-ms-client-principal-id",
    "x-ms-client-principal-name",
    "ocp-apim-subscription-key",
]

_SECRET_JSON_KEYS = (
    "access_token",
    "refresh_token",
    "id_token",
    "client_secret",
    "assertion",
    "primaryMasterKey",
    "secondaryMasterKey",
)


_TELEMETRY_HOST_MARKERS = (
    "applicationinsights.azure.com",
    "livediagnostics.monitor.azure.com",
    "monitor.azure.com",
    "dc.services.visualstudio.com",
)


def _drop_telemetry(request):
    """Drop telemetry traffic and scrub requests so cassettes are safe + replayable."""
    host = (request.host or "").lower()
    if any(marker in host for marker in _TELEMETRY_HOST_MARKERS):
        return None

    import json
    import re

    # Normalize real Azure resource hosts into the contract placeholders used in replay.
    uri = request.uri
    uri = re.sub(
        r"https://[^/]+\\.blob\\.core\\.windows\\.net",
        "https://contract.blob.core.windows.net",
        uri,
    )
    uri = re.sub(
        r"https://[^/]+\\.documents\\.azure\\.com(?::443)?",
        "https://contract.documents.azure.com:443",
        uri,
    )
    uri = re.sub(
        r"https://[^/]+\\.services\\.ai\\.azure\\.com",
        "https://contract.services.ai.azure.com",
        uri,
    )
    uri = re.sub(
        r"https://[^/]+\\.openai\\.azure\\.com",
        "https://contract.openai.azure.com",
        uri,
    )

    # Redact large/sensitive JSON payload fields (matching does not include body).
    body = request.body
    if body:
        try:
            text = (
                body.decode("utf-8", "replace")
                if isinstance(body, (bytes, bytearray))
                else str(body)
            )
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                for k in ("messages", "tools", "history"):
                    if k in parsed:
                        parsed[k] = "[REDACTED]"
                body = json.dumps(parsed).encode()
        except (ValueError, TypeError, UnicodeDecodeError):
            # Best-effort scrubbing: if payload is not parseable JSON, keep body unchanged.
            pass

    return request._replace(uri=uri, body=body)


def _scrub_response(response):
    """Redact credentials from recorded bodies before they hit disk."""
    body = response.get("body", {}).get("string")
    if not body:
        return response
    text = body.decode("utf-8", "replace") if isinstance(body, bytes) else str(body)
    if not any(key in text for key in _SECRET_JSON_KEYS):
        return response
    import json
    import re

    try:
        parsed = json.loads(text)
    except (ValueError, TypeError):
        for key in _SECRET_JSON_KEYS:
            text = re.sub(rf'("{key}"\s*:\s*)"[^"]*"', r'\1"[REDACTED]"', text)
        response["body"]["string"] = text.encode()
        return response

    def _walk(node):
        if isinstance(node, dict):
            return {
                k: ("[REDACTED]" if k in _SECRET_JSON_KEYS else _walk(v))
                for k, v in node.items()
            }
        if isinstance(node, list):
            return [_walk(v) for v in node]
        return node

    response["body"]["string"] = json.dumps(_walk(parsed)).encode()
    return response


@pytest.fixture(scope="session")
def vcr_config():
    return {
        # `record_mode` is deliberately NOT set here. pytest_recording._vcr
        # does `if "record_mode" in merged_config: record_mode = ...`, so a
        # value in this dict overrides --record-mode from the CLI outright and
        # a recording run silently stays in replay. The plugin already
        # defaults to "none", which is the guarantee we want: an outbound call
        # with no cassette raises instead of reaching the network.
        "filter_headers": [(h, "[REDACTED]") for h in _SECRET_HEADERS],
        "filter_post_data_parameters": [
            ("client_secret", "[REDACTED]"),
            ("assertion", "[REDACTED]"),
            ("refresh_token", "[REDACTED]"),
            ("code", "[REDACTED]"),
        ],
        "before_record_response": _scrub_response,
        # Generated requests vary by design, so the recorded upstream call
        # must match on the endpoint, not on the exact payload. Without this
        # every fuzzed variant would miss its cassette.
        "match_on": ["method", "scheme", "host", "port", "path"],
        "allow_playback_repeats": True,
        # The ASGI call is in-process (no socket); only the app's own
        # outbound traffic is of interest.
        "ignore_localhost": True,
        "ignore_hosts": [
            "testserver",
            "localhost",
            "127.0.0.1",
            "::1",
        ],
        # Telemetry is not part of any contract — never record it, never
        # count its misses as findings.
        "before_record_request": _drop_telemetry,
        "decode_compressed_response": True,
    }


@pytest.fixture(scope="module")
def vcr_cassette_dir(request):
    return str(Path(__file__).parent / "cassettes" / request.module.__name__)


@schemathesis.hook("map_case")
def force_stable_session_id(_, case):
    if case.meta and case.meta.generation.mode is GenerationMode.NEGATIVE:
        return case

    if case.path in {
        "/api/v4/chat/message",
        "/api/v4/chat/message/stream",
    }:
        if isinstance(case.body, dict):
            case.body["session_id"] = "00000000-0000-0000-0000-000000000123"

    if isinstance(case.path_parameters, dict):
        for k in ("file_id", "session_id"):
            if k in case.path_parameters:
                case.path_parameters[k] = "contract-fixed-id"

    return case
