/**
 * Shared type definitions for chat, products, and orders.
 *
 * Extracted from: microsoft/customer-chatbot-solution-accelerator (src/App/src/lib/types.ts)
 * Adapted for MACAE: added intent/agent metadata fields used by IntentRouter.
 */

/* ── Products ────────────────────────────────────────────────── */

export interface Product {
    id: string;
    title: string;
    price: number;
    originalPrice?: number;
    rating: number;
    reviewCount: number;
    image: string;
    category: string;
    inStock: boolean;
    description?: string;
}

/* ── Orders ──────────────────────────────────────────────────── */

export interface Order {
    orderNumber: string;
    status: string;
    orderDate: string;
    items: OrderItem[];
    subtotal: number;
    tax: number;
    total: number;
    shippingAddress: string;
}

export interface OrderItem {
    name: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
}

/* ── Cart ─────────────────────────────────────────────────────── */

export interface CartItem {
    product: Product;
    quantity: number;
}

/* ── Chat Messages ────────────────────────────────────────────── */

export interface ChatMessage {
    id: string;
    content: string;
    role: 'user' | 'assistant';
    timestamp: Date;
    typing?: boolean;
    /** Structured data parsed from AI response text */
    recommendedProducts?: Product[];
    parsedOrders?: Order[];
    parsedProducts?: Product[];
    /** MACAE-specific: IntentRouter metadata */
    intent?: string;
    agent?: string;
    confidence?: number;
    /** Tool activity events from agent (function calls, MCP tools, etc.) */
    toolActivity?: Array<{
        activity: 'calling' | 'result' | 'thinking';
        tool: string;
        server?: string;
        success?: boolean;
    }>;
    /** Files generated by Code Interpreter — persisted from Cosmos metadata */
    generatedFiles?: Array<{
        file_id: string;
        filename: string;
        container_id?: string | null;
        download_url: string;
    }>;
}

/* ── Chat Sessions ────────────────────────────────────────────── */

export interface ChatSessionSummary {
    id: string;
    user_id: string;
    session_name: string;
    message_count: number;
    created_at: string;
    updated_at: string;
    last_message_at: string | null;
    is_active: boolean;
}

export interface ChatSessionFull extends ChatSessionSummary {
    messages: Array<{
        id: string;
        content: string;
        sender: string;
        timestamp: string;
        metadata: Record<string, unknown>;
    }>;
}

/* ── Filters & Sorting ────────────────────────────────────────── */

export interface FilterOptions {
    category: string;
    minPrice: number;
    maxPrice: number;
    minRating: number;
    inStockOnly: boolean;
}

export interface SortOption {
    value: string;
    label: string;
}

export type SortBy = 'name' | 'price-asc' | 'price-desc' | 'rating' | 'newest';
